### ISSUE TITLE
Key Error: 'sapi5'

### ISSUE THREAD

**Issue by MatharuG** [ValentinGenard/Jarvis-artificial-intelligence#5]
Hello Valentin and/or other GitHub users!
I'm trying to use the JARVISE AI (Jarvis+newengine.py), but it doesn't run anymore.
Yesterday worked just fine, then today:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Python\lib\weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Matheus Haro/PycharmProjects/Jarvis AI/Jarvis+newengine.py", line 12, in <module>
    engine = pyttsx3.init('sapi5')
  File "C:\Python\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Python\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Python\lib\site-packages\pyttsx3\driver.py", line 52, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
  File "C:\Python\lib\site-packages\pyttsx3\drivers\sapi5.py", line 23, in buildDriver
    return SAPI5Driver(proxy)
  File "C:\Python\lib\site-packages\pyttsx3\drivers\sapi5.py", line 43, in __init__
    self.setProperty('voice', self.getProperty('voice'))
  File "C:\Python\lib\site-packages\pyttsx3\drivers\sapi5.py", line 78, in getProperty
    return self._tts.Voice.Id
  File "C:\Python\lib\site-packages\win32com\client\__init__.py", line 474, in __getattr__
    return self._ApplyTypes_(*args)
  File "C:\Python\lib\site-packages\win32com\client\__init__.py", line 467, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
pywintypes.com_error: (-2147352567, 'Exceção.', (0, None, None, None, 0, -2147221164), None)

Can someone help me?
Thanks!

**Comment by MatharuG** [comment]
I discovered the issue.
I've tried installing other voices, like EN-GB Hazel, or PT-BR Heloisa, but that was the problem...
Guess I'm stuck with EN-US Anna...

**Comment by MatharuG** [comment]
I discovered the issue.
I've tried installing other voices, like EN-GB Hazel, or PT-BR Heloisa, but that was the problem...
Guess I'm stuck with EN-US Anna...
